### ISSUE TITLE
CT: lots of IOType errors

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#110]
I did some basic PhET-iO instrumentation today for Fourier today, to sanity check where the implementation is at.  There are no errors when running Studio from phetmarks with `studio/?sim=fourier-making-waves&phetioElementsDisplay=all&log&sound=muted&showAnswers`.  But there are lots of errors in CT. Here they are:

---

> fourier-making-waves : fuzz : built-phet-io
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/fourier-making-waves/build/phet-io/fourier-making-waves_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1627516854282%22%2C%22timestamp%22%3A1627520432993%7D&fuzz&memoryLimit=1000&phetioStandalone
Query: fuzz&memoryLimit=1000&phetioStandalone
Uncaught TypeError: Cannot read property 'typeName' of undefined
TypeError: Cannot read property 'typeName' of undefined
at h (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/fourier-making-waves/build/phet-io/fourier-making-waves_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1627516854282%22%2C%22timestamp%22%3A1627520432993%7D&fuzz&memoryLimit=1000&phetioStandalone:867:199999)
at Object.getData (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/fourier-making-waves/build/phet-io/fourier-making-waves_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1627516854282%22%2C%22timestamp%22%3A1627520432993%7D&fuzz&memoryLimit=1000&phetioStandalone:867:7096)
at b.phetioStartEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/fourier-making-waves/build/phet-io/fourier-making-waves_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1627516854282%22%2C%22timestamp%22%3A1627520432993%7D&fuzz&memoryLimit=1000&phetioStandalone:867:183363)
at b._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/fourier-making-waves/build/phet-io/fourier-making-waves_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1627516854282%22%2C%22timestamp%22%3A1627520432993%7D&fuzz&memoryLimit=1000&phetioStandalone:867:6981)
at b.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/fourier-making-waves/build/phet-io/fourier-making-waves_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1627516854282%22%2C%22timestamp%22%3A1627520432993%7D&fuzz&memoryLimit=1000&phetioStandalone:867:6595)
at b.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/fourier-making-waves/build/phet-io/fourier-making-waves_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1627516854282%22%2C%22timestamp%22%3A1627520432993%7D&fuzz&memoryLimit=1000&phetioStandalone:867:7638)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/fourier-making-waves/build/phet-io/fourier-making-waves_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1627516854282%22%2C%22timestamp%22%3A1627520432993%7D&fuzz&memoryLimit=1000&phetioStandalone:867:1337422
at n.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/fourier-making-waves/build/phet-io/fourier-making-waves_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1627516854282%22%2C%22timestamp%22%3A1627520432993%7D&fuzz&memoryLimit=1000&phetioStandalone:867:12420)
at B._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/fourier-making-waves/build/phet-io/fourier-making-waves_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1627516854282%22%2C%22timestamp%22%3A1627520432993%7D&fuzz&memoryLimit=1000&phetioStandalone:867:7185)
at B.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/fourier-making-waves/build/phet-io/fourier-making-waves_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1627516854282%22%2C%22timestamp%22%3A1627520432993%7D&fuzz&memoryLimit=1000&phetioStandalone:867:6595)
id: Bayes Chrome
Snapshot from 7/28/2021, 6:00:54 PM

---

> fourier-making-waves : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/fourier-making-waves/fourier-making-waves_en.html?continuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1627516854282%22%2C%22timestamp%22%3A1627518449877%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: fell back to default state for fourierMakingWaves.discreteScreen.model.xAxisDescriptionProperty, should it be marked phetioState: false, or have a custom state method in a more specific IO Type?
Error: Assertion failed: fell back to default state for fourierMakingWaves.discreteScreen.model.xAxisDescriptionProperty, should it be marked phetioState: false, or have a custom state method in a more specific IO Type?
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/assert/js/assert.js:25:13)
at Object.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/tandem/js/types/IOType.js:406:15)
at IOType.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/tandem/js/types/IOType.js:157:36)
at PhetioStateEngine.getValueJSON (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io/js/PhetioStateEngine.js:107:49)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io/js/PhetioStateEngine.js:166:34
at Array.forEach (<anonymous>)
at PhetioStateEngine.getState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io/js/PhetioStateEngine.js:162:38)
at PhetioStateEngine.initialize (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io/js/PhetioStateEngine.js:476:30)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io/js/phetioEngine.js:228:32
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/axon/js/TinyEmitter.js:86:9)
id: Bayes Chrome
Snapshot from 7/28/2021, 6:00:54 PM

---

> fourier-making-waves : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io-wrappers/mirror-inputs/?sim=fourier-making-waves&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1627516854282%22%2C%22timestamp%22%3A1627518610995%7D
Uncaught Error: Uncaught Error: Assertion failed: fell back to default state for fourierMakingWaves.discreteScreen.model.xAxisDescriptionProperty, should it be marked phetioState: false, or have a custom state method in a more specific IO Type?
Error: Assertion failed: fell back to default state for fourierMakingWaves.discreteScreen.model.xAxisDescriptionProperty, should it be marked phetioState: false, or have a custom state method in a more specific IO Type?
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/assert/js/assert.js:25:13)
at Object.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/tandem/js/types/IOType.js:406:15)
at IOType.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/tandem/js/types/IOType.js:157:36)
at PhetioStateEngine.getValueJSON (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io/js/PhetioStateEngine.js:107:49)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io/js/PhetioStateEngine.js:166:34
at Array.forEach (<anonymous>)
at PhetioStateEngine.getState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io/js/PhetioStateEngine.js:162:38)
at PhetioStateEngine.initialize (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io/js/PhetioStateEngine.js:476:30)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io/js/phetioEngine.js:228:32
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/axon/js/TinyEmitter.js:86:9)
id: Bayes Chrome
Snapshot from 7/28/2021, 6:00:54 PM

---

> fourier-making-waves : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/studio/?sim=fourier-making-waves&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1627516854282%22%2C%22timestamp%22%3A1627521434375%7D
Uncaught Error: Uncaught Error: Assertion failed: fell back to default state for fourierMakingWaves.discreteScreen.model.xAxisDescriptionProperty, should it be marked phetioState: false, or have a custom state method in a more specific IO Type?
Error: Assertion failed: fell back to default state for fourierMakingWaves.discreteScreen.model.xAxisDescriptionProperty, should it be marked phetioState: false, or have a custom state method in a more specific IO Type?
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/assert/js/assert.js:25:13)
at Object.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/tandem/js/types/IOType.js:406:15)
at IOType.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/tandem/js/types/IOType.js:157:36)
at PhetioStateEngine.getValueJSON (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io/js/PhetioStateEngine.js:107:49)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io/js/PhetioStateEngine.js:166:34
at Array.forEach (<anonymous>)
at PhetioStateEngine.getState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io/js/PhetioStateEngine.js:162:38)
at PhetioStateEngine.initialize (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io/js/PhetioStateEngine.js:476:30)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io/js/phetioEngine.js:228:32
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/axon/js/TinyEmitter.js:86:9)
id: Bayes Chrome
Snapshot from 7/28/2021, 6:00:54 PM

---

> fourier-making-waves : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io-wrappers/phet-io-wrappers-tests.html?sim=fourier-making-waves&phetioDebug
3 out of 4 tests passed. 1 failed.
SimTests: fourier-making-waves: iframe API failed:
Uncaught Error: Uncaught Error: Assertion failed: fell back to default state for fourierMakingWaves.discreteScreen.model.xAxisDescriptionProperty, should it be marked phetioState: false, or have a custom state method in a more specific IO Type?
Error: Assertion failed: fell back to default state for fourierMakingWaves.discreteScreen.model.xAxisDescriptionProperty, should it be marked phetioState: false, or have a custom state method in a more specific IO Type?
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/assert/js/assert.js:25:13)
at Object.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/tandem/js/types/IOType.js:406:15)
at IOType.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/tandem/js/types/IOType.js:157:36)
at PhetioStateEngine.getValueJSON (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io/js/PhetioStateEngine.js:107:49)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io/js/PhetioStateEngine.js:166:34
at Array.forEach (<anonymous>)
at PhetioStateEngine.getState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io/js/PhetioStateEngine.js:162:38)
at PhetioStateEngine.initialize (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io/js/PhetioStateEngine.js:476:30)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io/js/phetioEngine.js:228:32
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/axon/js/TinyEmitter.js:86:9)
> 
> Uncaught Error: Uncaught Error: Assertion failed: fell back to default state for fourierMakingWaves.discreteScreen.model.xAxisDescriptionProperty, should it be marked phetioState: false, or have a custom state method in a more specific IO Type?Error: Assertion failed: fell back to default state for fourierMakingWaves.discreteScreen.model.xAxisDescriptionProperty, should it be marked phetioState: false, or have a custom state method in a more specific IO Type?
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/assert/js/assert.js:25:13)
at Object.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/tandem/js/types/IOType.js:406:15)
at IOType.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/tandem/js/types/IOType.js:157:36)
at PhetioStateEngine.getValueJSON (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io/js/PhetioStateEngine.js:107:49)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io/js/PhetioStateEngine.js:166:34
at Array.forEach (<anonymous>)
at PhetioStateEngine.getState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io/js/PhetioStateEngine.js:162:38)
at PhetioStateEngine.initialize (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io/js/PhetioStateEngine.js:476:30)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io/js/phetioEngine.js:228:32
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/axon/js/TinyEmitter.js:86:9)
id: Bayes Chrome
Snapshot from 7/28/2021, 6:00:54 PM

--- 

> fourier-making-waves : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io-wrappers/phet-io-wrappers-tests.html?sim=fourier-making-waves
3 out of 4 tests passed. 1 failed.
SimTests: fourier-making-waves: iframe API failed:
Uncaught Error: Uncaught Error: Assertion failed: fell back to default state for fourierMakingWaves.discreteScreen.model.xAxisDescriptionProperty, should it be marked phetioState: false, or have a custom state method in a more specific IO Type?
Error: Assertion failed: fell back to default state for fourierMakingWaves.discreteScreen.model.xAxisDescriptionProperty, should it be marked phetioState: false, or have a custom state method in a more specific IO Type?
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/assert/js/assert.js:25:13)
at Object.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/tandem/js/types/IOType.js:406:15)
at IOType.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/tandem/js/types/IOType.js:157:36)
at PhetioStateEngine.getValueJSON (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io/js/PhetioStateEngine.js:107:49)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io/js/PhetioStateEngine.js:166:34
at Array.forEach (<anonymous>)
at PhetioStateEngine.getState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io/js/PhetioStateEngine.js:162:38)
at PhetioStateEngine.initialize (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io/js/PhetioStateEngine.js:476:30)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io/js/phetioEngine.js:228:32
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/axon/js/TinyEmitter.js:86:9)
> 
> Uncaught Error: Uncaught Error: Assertion failed: fell back to default state for fourierMakingWaves.discreteScreen.model.xAxisDescriptionProperty, should it be marked phetioState: false, or have a custom state method in a more specific IO Type?Error: Assertion failed: fell back to default state for fourierMakingWaves.discreteScreen.model.xAxisDescriptionProperty, should it be marked phetioState: false, or have a custom state method in a more specific IO Type?
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/assert/js/assert.js:25:13)
at Object.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/tandem/js/types/IOType.js:406:15)
at IOType.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/tandem/js/types/IOType.js:157:36)
at PhetioStateEngine.getValueJSON (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io/js/PhetioStateEngine.js:107:49)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io/js/PhetioStateEngine.js:166:34
at Array.forEach (<anonymous>)
at PhetioStateEngine.getState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io/js/PhetioStateEngine.js:162:38)
at PhetioStateEngine.initialize (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io/js/PhetioStateEngine.js:476:30)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/phet-io/js/phetioEngine.js:228:32
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627516854282/axon/js/TinyEmitter.js:86:9)
id: Bayes Chrome
Snapshot from 7/28/2021, 6:00:54 PM

**Comment by pixelzoom** [comment]
Looks like these are all the same error:

> Uncaught Error: Uncaught Error: Assertion failed: fell back to default state for fourierMakingWaves.discreteScreen.model.xAxisDescriptionProperty, should it be marked phetioState: false, or have a custom state method in a more specific IO Type?

**Comment by pixelzoom** [comment]
Here's the definition of `xAxisDescriptionProperty`:

```js
    // {Property.<AxisDescription>} the x-axis description is shared by the Harmonics and Sum charts.
    const xAxisDescriptionProperty = new Property( DEFAULT_X_AXIS_DESCRIPTION, {
      validValues: X_AXIS_DESCRIPTIONS,
      tandem: options.tandem.createTandem( 'xAxisDescriptionProperty' )
    } );
```

This will eventually need `phetioType: PropertyIO( AxisDescriptionIO )`.  But `AxisDescriptionIO` doesn't exist yet.  So I'm going to uninstrument `xAxisDescriptionProperty` for now, to make these CT errors go away.

**Comment by pixelzoom** [comment]
In DiscreteModel.js, I had to uninstrument both `xAxisDescriptionProperty ` and `harmonicsYAxisDescriptionProperty`.  I'll leave this issue open until CT reports all clear.

**Comment by pixelzoom** [comment]
More similar IOType errors in CT:

```
fourier-making-waves : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627572577609/fourier-making-waves/fourier-making-waves_en.html?continuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1627572577609%22%2C%22timestamp%22%3A1627573634288%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: fell back to default state for fourierMakingWaves.discreteScreen.model.charts.amplitudesChart, should it be marked phetioState: false, or have a custom state method in a more specific IO Type?
Error: Assertion failed: fell back to default state for fourierMakingWaves.discreteScreen.model.charts.amplitudesChart, should it be marked phetioState: false, or have a custom state method in a more specific IO Type?
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627572577609/assert/js/assert.js:25:13)
at Object.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627572577609/tandem/js/types/IOType.js:406:15)
at IOType.toStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627572577609/tandem/js/types/IOType.js:157:36)
at PhetioStateEngine.getValueJSON (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627572577609/phet-io/js/PhetioStateEngine.js:107:49)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627572577609/phet-io/js/PhetioStateEngine.js:166:34
at Array.forEach (<anonymous>)
at PhetioStateEngine.getState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627572577609/phet-io/js/PhetioStateEngine.js:162:38)
at PhetioStateEngine.initialize (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627572577609/phet-io/js/PhetioStateEngine.js:476:30)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627572577609/phet-io/js/phetioEngine.js:228:32
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627572577609/axon/js/TinyEmitter.js:86:9)
id: Bayes Chrome
Snapshot from 7/29/2021, 9:29:37 AM
```

**Comment by pixelzoom** [comment]
I ran with `?ea&brand=phet-io&phetioStandalone&fuzz`, identified a few more problems, and uninstrumented some things.  I'll leave this issue open until CT reports all clear.

**Comment by pixelzoom** [comment]
CT has been clear for 2 cycles, closing.
