### ISSUE TITLE
CT: A rectangle needs to have a finite y1 (Infinity)

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#115]
Occuring at the same time as https://github.com/phetsims/fourier-making-waves/issues/116, but probably not related.

```
fourier-making-waves : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627948155061/fourier-making-waves/fourier-making-waves_en.html?continuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1627948155061%22%2C%22timestamp%22%3A1627991830969%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: A rectangle needs to have a finite y1 (Infinity)
Error: Assertion failed: A rectangle needs to have a finite y1 (Infinity)
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627948155061/assert/js/assert.js:25:13)
at AxisLine.invalidateLine (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627948155061/scenery/js/nodes/Line.js:398:15)
at AxisLine.setLine (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627948155061/scenery/js/nodes/Line.js:148:10)
at AxisLine.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627948155061/bamboo/js/AxisLine.js:61:12)
at changedListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627948155061/bamboo/js/AxisLine.js:44:40)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627948155061/axon/js/TinyEmitter.js:86:9)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627948155061/axon/js/Emitter.js:39:24
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627948155061/axon/js/Action.js:227:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627948155061/axon/js/Emitter.js:64:19)
at ChartTransform.setModelYRange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627948155061/bamboo/js/ChartTransform.js:321:27)
id: Bayes Chrome
Snapshot from 8/2/2021, 5:49:15 PM
```

**Comment by pixelzoom** [comment]
Reproduced in unbuild mode with `?brand=phet&eall&fuzz`, here's the stack trace:

```
window.assertions.assertFunction (assert.js:25)
invalidateLine (Line.js:398)
setLine (Line.js:148)
update (AxisLine.js:61)
changedListener (AxisLine.js:44)
emit (TinyEmitter.js:86)
(anonymous) (Emitter.js:39)
execute (Action.js:227)
emit (Emitter.js:64)
setModelYRange (ChartTransform.js:321)
(anonymous) (WavePacketComponentsChartNode.js:125)
```

WavePacketComponentsChartNode.js line 125:

```js
        maxY = 1.1 * maxY; // add a bit of padding
125     this.chartTransform.setModelYRange( new Range( -maxY, maxY ) );
```

**Comment by pixelzoom** [comment]
This is failing because:
(a) ChartTransform's modelYRange is being set to something very small, `Range {_min: -3.348051012351776e-309, _max: 3.348051012351776e-309}`, and 
(b) ChartTransform `modelToView` is failing to handle small numbers, specifically in the calls to `Util.linear`.

**Comment by pixelzoom** [comment]
Problem (a) above went away when I completed the implementation of the Components chart in the Wave Packet screen.

Problem (b) is still a problem, but no longer affects this sim.

CT is clear. Closing.
