### ISSUE TITLE
CT: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#119]
```
fourier-making-waves : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628358306609/phet-io-wrappers/mirror-inputs/?sim=fourier-making-waves&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1628358306609%22%2C%22timestamp%22%3A1628360103219%7D
Uncaught Error: Uncaught RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
at HorizontalDimensionalArrowsNode.getCenterX (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628358306609/scenery/js/nodes/Node.js:3057:13)
at HorizontalDimensionalArrowsNode.get centerX [as centerX] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628358306609/scenery/js/nodes/Node.js:3068:17)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628358306609/fourier-making-waves/js/wavepacket/view/WidthIndicatorPlot.js:99:56
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628358306609/axon/js/Multilink.js:47:11)
at TinyStaticProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628358306609/axon/js/TinyEmitter.js:86:9)
at TinyStaticProperty.notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628358306609/axon/js/TinyStaticProperty.js:74:10)
at BackgroundNode.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628358306609/scenery/js/nodes/Node.js:1346:31)
at TinyStaticProperty.get (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628358306609/axon/js/TinyStaticProperty.js:38:10)
at TinyStaticProperty.get value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628358306609/axon/js/TinyProperty.js:53:17)
at BackgroundNode.getBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628358306609/scenery/js/nodes/Node.js:1887:32)
id: Bayes Chrome
Snapshot from 8/7/2021, 11:45:06 AM
```

**Comment by pixelzoom** [comment]
Another version of what appears to be the same error:

```
fourier-making-waves : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628304436541/fourier-making-waves/fourier-making-waves_en.html?continuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1628304436541%22%2C%22timestamp%22%3A1628322302762%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
at BackgroundNode.setCenterX (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628304436541/scenery/js/nodes/Node.js:3028:13)
at BackgroundNode.set centerX [as centerX] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628304436541/scenery/js/nodes/Node.js:3046:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628304436541/fourier-making-waves/js/wavepacket/view/WidthIndicatorPlot.js:99:32
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628304436541/axon/js/Multilink.js:47:11)
at TinyStaticProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628304436541/axon/js/TinyEmitter.js:86:9)
at TinyStaticProperty.notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628304436541/axon/js/TinyStaticProperty.js:74:10)
at BackgroundNode.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628304436541/scenery/js/nodes/Node.js:1346:31)
at TinyStaticProperty.get (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628304436541/axon/js/TinyStaticProperty.js:38:10)
at TinyStaticProperty.get value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628304436541/axon/js/TinyProperty.js:53:17)
at BackgroundNode.getBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628304436541/scenery/js/nodes/Node.js:1887:32)
id: Bayes Chrome
Snapshot from 8/6/2021, 8:47:16 PM
```

**Comment by pixelzoom** [comment]
Probably this code in WidthIndicatorPlot.js:

```js
    Property.multilink(
      [ backgroundNode.boundsProperty, dimensionalArrowsNode.boundsProperty ],
      () => {
        backgroundNode.centerX = dimensionalArrowsNode.centerX;
        backgroundNode.top = dimensionalArrowsNode.bottom;
      } );
```

**Comment by pixelzoom** [comment]
Fixed in the above commit. I'll leave this open until it's been clear for a couple of CT cycles.

**Comment by pixelzoom** [comment]
CT is clear, closing.
