### ISSUE TITLE
CT: unsupported equationForm

### ISSUE THREAD

**Issue by samreid** [phetsims/fourier-making-waves#238]
CT Showed this error today in the 9/21/2023 5:54:46pm column:

```
fourier-making-waves : fuzz : unbuilt : listenerOrderRandom
http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/fourier-making-waves/fourier-making-waves_en.html?continuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1695340486384%22%2C%22timestamp%22%3A1695346878978%7D&brand=phet&ea&fuzz&listenerOrder=random
Query: brand=phet&ea&fuzz&listenerOrder=random
Uncaught Error: Assertion failed: unsupported equationForm: PERIOD
```

Full details:

<details>

```

fourier-making-waves : fuzz : unbuilt : listenerOrderRandom
http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/fourier-making-waves/fourier-making-waves_en.html?continuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1695340486384%22%2C%22timestamp%22%3A1695346878978%7D&brand=phet&ea&fuzz&listenerOrder=random
Query: brand=phet&ea&fuzz&listenerOrder=random
Uncaught Error: Assertion failed: unsupported equationForm: PERIOD
Error: Assertion failed: unsupported equationForm: PERIOD
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/assert/js/assert.js:28:13)
at assert (EquationMarkup.ts:96:12)
at getSpaceMarkup (EquationMarkup.ts:56:15)
at getSpecificFormMarkup (EquationMarkup.ts:47:26)
at getGeneralFormMarkup (DiscreteSumEquationNode.ts:82:42)
at callback (Multilink.ts:111:10)
at listener (TinyEmitter.ts:123:8)
at emit (ReadOnlyProperty.ts:315:22)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1695340486384%2Ffourier-making-waves%2Ffourier-making-waves_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1695340486384%22%2C%22timestamp%22%3A1695346878978%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1695340486384%2Ffourier-making-waves%2Ffourier-making-waves_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1695340486384%22%2C%22timestamp%22%3A1695346878978%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/fourier-making-waves/fourier-making-waves_en.html?continuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1695340486384%22%2C%22timestamp%22%3A1695346878978%7D&brand=phet&ea&fuzz&listenerOrder=random
[CONSOLE] enabling assert
[CONSOLE] listenerOrder random seed: 503360
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed: unsupported equationForm: PERIOD
[PAGE ERROR] Error: Error: Assertion failed: unsupported equationForm: PERIOD
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/assert/js/assert.js:28:13)
at getSpaceMarkup (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/fourier-making-waves/js/common/view/EquationMarkup.js:85:13)
at Object.getSpecificFormMarkup (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/fourier-making-waves/js/common/view/EquationMarkup.js:52:16)
at Object.getGeneralFormMarkup (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/fourier-making-waves/js/common/view/EquationMarkup.js:44:27)
at http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/fourier-making-waves/js/discrete/view/DiscreteSumEquationNode.js:50:41
at listener (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/axon/js/Multilink.js:50:11)
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at EnumerationProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/axon/js/ReadOnlyProperty.js:239:23)
at EnumerationProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/axon/js/ReadOnlyProperty.js:188:14)
at EnumerationProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/axon/js/ReadOnlyProperty.js:173:12)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: unsupported equationForm: PERIOD
[PAGE ERROR] Error: Error: Assertion failed: unsupported equationForm: PERIOD
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/assert/js/assert.js:28:13)
at getSpaceMarkup (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/fourier-making-waves/js/common/view/EquationMarkup.js:85:13)
at Object.getSpecificFormMarkup (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/fourier-making-waves/js/common/view/EquationMarkup.js:52:16)
at http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/fourier-making-waves/js/discrete/view/ExpandedFormDialog.js:58:45
at listener (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/axon/js/Multilink.js:50:11)
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at NumberProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/axon/js/ReadOnlyProperty.js:239:23)
at NumberProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/axon/js/ReadOnlyProperty.js:188:14)
at NumberProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/axon/js/ReadOnlyProperty.js:173:12)
at NumberProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/axon/js/Property.js:58:11)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: unsupported equationForm: PERIOD
[PAGE ERROR] Error: Error: Assertion failed: unsupported equationForm: PERIOD
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/assert/js/assert.js:28:13)
at getSpaceMarkup (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/fourier-making-waves/js/common/view/EquationMarkup.js:85:13)
at Object.getSpecificFormMarkup (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/fourier-making-waves/js/common/view/EquationMarkup.js:52:16)
at http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/fourier-making-waves/js/discrete/view/ExpandedFormDialog.js:58:45
at listener (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/axon/js/Multilink.js:50:11)
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at DerivedProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/axon/js/ReadOnlyProperty.js:239:23)
at DerivedProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/axon/js/ReadOnlyProperty.js:188:14)
at DerivedProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/axon/js/ReadOnlyProperty.js:173:12)
at DerivedProperty.getDerivedPropertyListener (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/axon/js/DerivedProperty.js:111:13)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: reentry detected, value=0, oldValue=0.65
[PAGE ERROR] Error: Error: Assertion failed: reentry detected, value=0, oldValue=0.65
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/assert/js/assert.js:28:13)
at NumberProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/axon/js/ReadOnlyProperty.js:237:15)
at NumberProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/axon/js/ReadOnlyProperty.js:188:14)
at NumberProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/axon/js/ReadOnlyProperty.js:173:12)
at NumberProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/axon/js/Property.js:58:11)
at handleTrackEvent (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/sun/js/SliderTrack.js:84:21)
at DragListener.drag [as _dragListener] (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/sun/js/SliderTrack.js:104:9)
at DragListener.drag (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/scenery/js/listeners/PressListener.js:341:10)
at DragListener._dragAction.PhetioAction.parameters.name (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/scenery/js/listeners/DragListener.js:166:36)
at PhetioAction.execute (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/tandem/js/PhetioAction.js:132:17)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: reentry detected, value=1,0,0,0,0.6,0,0,0,0,0,0, oldValue=1,0,0,0,0,0,0,0,0,0.65,0
[PAGE ERROR] Error: Error: Assertion failed: reentry detected, value=1,0,0,0,0.6,0,0,0,0,0,0, oldValue=1,0,0,0,0,0,0,0,0,0.65,0
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/assert/js/assert.js:28:13)
at DerivedProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/axon/js/ReadOnlyProperty.js:237:15)
at DerivedProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/axon/js/ReadOnlyProperty.js:188:14)
at DerivedProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/axon/js/ReadOnlyProperty.js:173:12)
at DerivedProperty.getDerivedPropertyListener (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/axon/js/DerivedProperty.js:111:13)
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at NumberProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/axon/js/ReadOnlyProperty.js:239:23)
at NumberProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/axon/js/ReadOnlyProperty.js:188:14)
at NumberProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/axon/js/ReadOnlyProperty.js:173:12)
at NumberProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1695340486384/chipper/dist/js/axon/js/Property.js:58:11)
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 9/21/2023, 5:54:46 PM
```

</details>

**Comment by pixelzoom** [comment]
Looking back through CT cycles, I see similarly:

```
ourier-making-waves : fuzz : unbuilt : listenerOrderRandom
http://128.138.93.172/continuous-testing/ct-snapshots/1695288799944/fourier-making-waves/fourier-making-waves_en.html?continuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1695288799944%22%2C%22timestamp%22%3A1695298598174%7D&brand=phet&ea&fuzz&listenerOrder=random
Query: brand=phet&ea&fuzz&listenerOrder=random
Uncaught Error: Assertion failed: unsupported equationForm: ANGULAR_WAVE_NUMBER
Error: Assertion failed: unsupported equationForm: ANGULAR_WAVE_NUMBER
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1695288799944/assert/js/assert.js:28:13)
at assert (EquationMarkup.ts:155:12)
at getSpaceAndTimeMarkup (EquationMarkup.ts:62:15)
at getSpecificFormMarkup (EquationMarkup.ts:47:26)
at getGeneralFormMarkup (DiscreteSumEquationNode.ts:82:42)
at callback (Multilink.ts:111:10)
at listener (TinyEmitter.ts:123:8)
at emit (ReadOnlyProperty.ts:315:22)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1695288799944%2Ffourier-making-waves%2Ffourier-making-waves_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22fourier-making-
...
id: "Sparky Node Puppeteer"
Snapshot from 9/21/2023, 3:33:19 AM
```

**Comment by pixelzoom** [comment]
Here's another example:

```
fourier-making-waves : fuzz : unbuilt : listenerOrderRandom
http://128.138.93.172/continuous-testing/ct-snapshots/1695576926864/fourier-making-waves/fourier-making-waves_en.html?continuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1695576926864%22%2C%22timestamp%22%3A1695592020686%7D&brand=phet&ea&fuzz&listenerOrder=random
Query: brand=phet&ea&fuzz&listenerOrder=random
Uncaught Error: Assertion failed: unsupported equationForm: SPATIAL_WAVE_NUMBER
Error: Assertion failed: unsupported equationForm: SPATIAL_WAVE_NUMBER
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1695576926864/assert/js/assert.js:28:13)
at assert (EquationMarkup.ts:124:12)
at getTimeMarkup (EquationMarkup.ts:59:15)
at getSpecificFormMarkup (ExpandedFormDialog.ts:76:46)
at callback (Multilink.ts:111:10)
at listener (TinyEmitter.ts:123:8)
at emit (ReadOnlyProperty.ts:315:22)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (Property.ts:54:10)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1695576926864%2Ffourier-making-waves%2Ffourier-making-waves_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1695576926864%22%2C%22timestamp%22%3A1695592020686%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1695576926864%2Ffourier-making-waves%2Ffourier-making-waves_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1695576926864%22%2C%22timestamp%22%3A1695592020686%7D
...
id: "Sparky Node Puppeteer"
Snapshot from 9/24/2023, 11:35:26 AM
```

**Comment by pixelzoom** [comment]
Here's the failing assertion in EquationMarkup.ts:

```ts
function getSpaceMarkup( seriesType: SeriesType, equationForm: EquationForm, order: Order, amplitude: Amplitude ): string {
  assert && assert( [ EquationForm.HIDDEN, EquationForm.WAVELENGTH, EquationForm.SPATIAL_WAVE_NUMBER, EquationForm.MODE ].includes( equationForm ),
    `unsupported equationForm: ${equationForm}` );
```

**Comment by pixelzoom** [comment]
Also in ExpandedFormDialog.ts:

```ts
    Multilink.multilink(
      [ fourierSeries.numberOfHarmonicsProperty, fourierSeries.amplitudesProperty, domainProperty, seriesTypeProperty, equationFormProperty ],
      ( numberOfHarmonics, amplitudes, domain, seriesType, equationForm ) => {
...
          expandedSumMarkup += EquationMarkup.getSpecificFormMarkup( domain, seriesType, equationForm, order, amplitude );
...
      } );
```

**Comment by pixelzoom** [comment]
To manually reproduce the error that originates in DiscreteSumEquationNode.ts:

1. Run the sim with `?brand=phet&ea&debugger&listenerOrder=548659`
2. Go to Discrete screen
3. Change "Equation" combo box to "λ".
4. Change "Function of" combo box to "time (t)"

**Comment by pixelzoom** [comment]
DiscreteModel adjusts equationFormProperty to match domainProperty:

```ts
    // Ensure that the math form is appropriate for the Domain. EquationForm.MODE is supported for all Domain values.
    this.domainProperty.link( () => {
      if ( this.equationFormProperty.value !== EquationForm.MODE ) {
        this.equationFormProperty.value = EquationForm.HIDDEN;
      }
    } );
```

So the above commit handles the intermediate state by treating it like EquationForm.HIDDEN. 

I'll leave this open until I confirm that CT is happy.

**Comment by pixelzoom** [comment]
FYI, I spent 1.5 hours on this.  I'm not sure that it was worth it.
