### ISSUE TITLE
CT: no components

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#241]
Related to https://github.com/phetsims/fourier-making-waves/issues/240, moved to its own issue.

```
fourier-making-waves : fuzz : unbuilt : listenerOrderRandom
http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/fourier-making-waves/fourier-making-waves_en.html?continuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1704313793882%22%2C%22timestamp%22%3A1704314171619%7D&brand=phet&ea&fuzz&listenerOrder=random
Query: brand=phet&ea&fuzz&listenerOrder=random
Uncaught Error: Assertion failed: no components
Error: Assertion failed: no components
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/assert/js/assert.js:28:13)
at assert (WavePacketComponentsChart.ts:67:14)
at createComponentsDataSets (WavePacketSumChart.ts:118:67)
at derivation (DerivedProperty.ts:55:11)
at getDerivedValue (DerivedProperty.ts:179:17)
at listener (TinyEmitter.ts:123:8)
at emit (ReadOnlyProperty.ts:328:22)
at _notifyListeners (ReadOnlyProperty.ts:275:13)
at unguardedSet (ReadOnlyProperty.ts:259:11)
at set (DerivedProperty.ts:179:12)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1704313793882%2Ffourier-making-waves%2Ffourier-making-waves_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1704313793882%22%2C%22timestamp%22%3A1704314171619%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1704313793882%2Ffourier-making-waves%2Ffourier-making-waves_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1704313793882%22%2C%22timestamp%22%3A1704314171619%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/fourier-making-waves/fourier-making-waves_en.html?continuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1704313793882%22%2C%22timestamp%22%3A1704314171619%7D&brand=phet&ea&fuzz&listenerOrder=random
[CONSOLE] enabling assert
[CONSOLE] listenerOrder random seed: 974748
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed: no components
[PAGE ERROR] Error: Error: Assertion failed: no components
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/assert/js/assert.js:28:13)
at WavePacketComponentsChart.createComponentsDataSets (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/chipper/dist/js/fourier-making-waves/js/wavepacket/model/WavePacketComponentsChart.js:42:15)
at http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/chipper/dist/js/fourier-making-waves/js/wavepacket/model/WavePacketSumChart.js:75:66
at getDerivedValue (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/chipper/dist/js/axon/js/DerivedProperty.js:32:12)
at DerivedProperty.getDerivedPropertyListener (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/chipper/dist/js/axon/js/DerivedProperty.js:121:17)
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at DerivedProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/chipper/dist/js/axon/js/ReadOnlyProperty.js:252:23)
at DerivedProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/chipper/dist/js/axon/js/ReadOnlyProperty.js:201:14)
at DerivedProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/chipper/dist/js/axon/js/ReadOnlyProperty.js:186:12)
at DerivedProperty.getDerivedPropertyListener (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/chipper/dist/js/axon/js/DerivedProperty.js:121:13)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: reentry detected, value=, oldValue=
[PAGE ERROR] Error: Error: Assertion failed: reentry detected, value=, oldValue=
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/assert/js/assert.js:28:13)
at DerivedProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/chipper/dist/js/axon/js/ReadOnlyProperty.js:250:15)
at DerivedProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/chipper/dist/js/axon/js/ReadOnlyProperty.js:201:14)
at DerivedProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/chipper/dist/js/axon/js/ReadOnlyProperty.js:186:12)
at DerivedProperty.getDerivedPropertyListener (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/chipper/dist/js/axon/js/DerivedProperty.js:121:13)
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at NumberProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/chipper/dist/js/axon/js/ReadOnlyProperty.js:252:23)
at NumberProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/chipper/dist/js/axon/js/ReadOnlyProperty.js:201:14)
at NumberProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/chipper/dist/js/axon/js/ReadOnlyProperty.js:186:12)
at NumberProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/chipper/dist/js/axon/js/Property.js:58:11)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: reentry detected, value=12.46, oldValue=3.141592653589793
[PAGE ERROR] Error: Error: Assertion failed: reentry detected, value=12.46, oldValue=3.141592653589793
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/assert/js/assert.js:28:13)
at NumberProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/chipper/dist/js/axon/js/ReadOnlyProperty.js:250:15)
at NumberProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/chipper/dist/js/axon/js/ReadOnlyProperty.js:201:14)
at NumberProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/chipper/dist/js/axon/js/ReadOnlyProperty.js:186:12)
at NumberProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/chipper/dist/js/axon/js/Property.js:58:11)
at DragListener.drag [as _dragListener] (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/chipper/dist/js/sun/js/Slider.js:275:25)
at DragListener.drag (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/chipper/dist/js/scenery/js/listeners/PressListener.js:341:10)
at DragListener._dragAction.PhetioAction.parameters.name (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/chipper/dist/js/scenery/js/listeners/DragListener.js:171:36)
at PhetioAction.execute (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/chipper/dist/js/tandem/js/PhetioAction.js:133:17)
at DragListener.drag (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/chipper/dist/js/scenery/js/listeners/DragListener.js:304:22)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: no components
[PAGE ERROR] Error: Error: Assertion failed: no components
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/assert/js/assert.js:28:13)
at WavePacketComponentsChart.createComponentsDataSets (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/chipper/dist/js/fourier-making-waves/js/wavepacket/model/WavePacketComponentsChart.js:42:15)
at http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/chipper/dist/js/fourier-making-waves/js/wavepacket/model/WavePacketSumChart.js:75:66
at getDerivedValue (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/chipper/dist/js/axon/js/DerivedProperty.js:32:12)
at DerivedProperty.getDerivedPropertyListener (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/chipper/dist/js/axon/js/DerivedProperty.js:121:17)
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at EnumerationProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/chipper/dist/js/axon/js/ReadOnlyProperty.js:252:23)
at EnumerationProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/chipper/dist/js/axon/js/ReadOnlyProperty.js:201:14)
at EnumerationProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/chipper/dist/js/axon/js/ReadOnlyProperty.js:186:12)
at EnumerationProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1704313793882/chipper/dist/js/axon/js/Property.js:58:11)
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 1/3/2024, 1:29:53 PM
```

**Comment by pixelzoom** [comment]
To reproduce manually:

1. Run http://localhost:8080/fourier-making-waves/fourier-making-waves_en.html?brand=phet&ea&debugger&audio=disabled&listenerOrder=random(974748)
2. Go to the Wave Packet screen.
3. Drag the "Component Spacing" slider to '0'

**Comment by pixelzoom** [comment]
I'm giving up on this and opting out of `listOrderRandom` tests for CT.  See https://github.com/phetsims/fourier-making-waves/issues/240#issuecomment-1876091788.
