### ISSUE TITLE
CT: all data sets must have the same number of points

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#25]
Factored out of https://github.com/phetsims/fourier-making-waves/issues/24:

```
fourier-making-waves : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607652969222/fourier-making-waves/fourier-making-waves_en.html?continuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1607652969222%22%2C%22timestamp%22%3A1607688562633%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: all data sets must have the same number of points
Error: Assertion failed: all data sets must have the same number of points
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607652969222/assert/js/assert.js:25:13)
at createSumDataSet (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607652969222/fourier-making-waves/js/discrete/view/HarmonicsChart.js:226:3)
at updateSum (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607652969222/fourier-making-waves/js/discrete/view/HarmonicsChart.js:93:39)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607652969222/fourier-making-waves/js/discrete/view/HarmonicsChart.js:141:9
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607652969222/axon/js/TinyEmitter.js:71:18)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607652969222/axon/js/Property.js:280:25)
at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607652969222/axon/js/Property.js:178:14)
at NumberProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607652969222/axon/js/Property.js:350:32)
at updateAmplitudes (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607652969222/fourier-making-waves/js/discrete/model/DiscreteModel.js:104:69)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607652969222/fourier-making-waves/js/discrete/model/DiscreteModel.js:112:52
id: Bayes Chrome
Snapshot from 12/10/2020, 7:16:09 PM
```

**Comment by pixelzoom** [comment]
I have not been able to reproduce this locally with `?brand=phet&ea&screens=1&fuzz`.   It could be related to #24, since it's the same line of code.  I'll leave this open and see if CT is still having a problem with it.

**Comment by pixelzoom** [comment]
CT is still failing.

**Comment by pixelzoom** [comment]
This is now occurring for State wrapper test only, see below.   I'm guessing that when state is restored, this (invalid) intermediate state occurs.

```
fourier-making-waves : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607772371295/phet-io-wrappers/state/?sim=fourier-making-waves&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1607772371295%22%2C%22timestamp%22%3A1607774328170%7D
Uncaught Error: Assertion failed: all data sets must have the same number of points
Error: Assertion failed: all data sets must have the same number of points
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607772371295/assert/js/assert.js:25:13)
at createSumDataSet (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607772371295/fourier-making-waves/js/discrete/view/HarmonicsChart.js:278:13)
at updateSumDataSet (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607772371295/fourier-making-waves/js/discrete/view/HarmonicsChart.js:211:30)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607772371295/fourier-making-waves/js/discrete/view/HarmonicsChart.js:117:9
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607772371295/axon/js/TinyEmitter.js:71:18)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607772371295/axon/js/Property.js:280:25)
at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607772371295/axon/js/Property.js:178:14)
at NumberProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607772371295/axon/js/Property.js:350:32)
at updateAmplitudes (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607772371295/fourier-making-waves/js/discrete/model/DiscreteModel.js:104:69)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607772371295/fourier-making-waves/js/discrete/model/DiscreteModel.js:112:52
id: Bayes Chrome
Snapshot from 12/12/2020, 4:26:11 AM
```

**Comment by pixelzoom** [comment]
At this stage of implementation,  I don't care whether there are State wrapper problems, I fully expect that there will be problems, and I care only about being to incrementally add tandems and inspect the Studio tree. 

@zepumph @samreid How do I tell CT that my sim is not ready for State wrapper testing?

**Comment by pixelzoom** [comment]
I did find a way to fail this assertion in unbuilt brand=phet:

1. Start the sim with ?ea
2. Go to Discrete screen
3. Set Waveform combo box to "wave packet"
4. Set Harmonics picker to 10
5. Set Harmonics picker to 11

**Comment by samreid** [comment]
As I mentioned in https://github.com/phetsims/aqua/issues/113#issuecomment-743932825

> We have a list to opt-out of phet-io state tests in https://github.com/phetsims/perennial/blob/master/data/phet-io-state-unsupported.

**Comment by pixelzoom** [comment]
Thanks, I'm aware of phet-io-state-unsupported.  My question is how do I opt out of **_all_** PhET-iO tests.  My sim is not going to support PhET-iO until > 1.0, but I still need to add a minimal amount of PhET-iO instrumentation in order to confirm that I'm going to be able to meet design requirements.

If it's really impossible to add the PhET-iO modes to phetmarks without enabling CT PhET-iO tests, then I'll just remove my sim from phetmarks and create my own bookmarks.  But that seems really silly, not to mention inconvenient.

**Comment by pixelzoom** [comment]
What's going on here... 

When number of harmonics is changed while a preset waveform is selected, it updates the amplitudes for each of the harmonics.  In DiscreteModel:

```js
        const amplitudes = waveform.getAmplitudes( numberOfHarmonics, waveType );
...
        for ( let i = 0; i < numberOfHarmonics; i++ ) {
          this.fourierSeries.harmonics[ i ].amplitudeProperty.value = amplitudes[ i ];
        }
```

Over in HarmonicsChart, when a harmonic's amplitude changes, its plot and the sum are updated:

```js
      plot.harmonic.amplitudeProperty.lazyLink( () => {
        updateOneHarmonicPlot( plot, this.chartTransform.modelXRange,
          fourierSeries.numberOfHarmonicsProperty.value, domainProperty.value, waveTypeProperty.value, tProperty.value );
        chartCanvasNode.update();
        updateSumDataSet( this.sumDataSetProperty, harmonicPlots, fourierSeries.numberOfHarmonicsProperty.value );
      } );
```

The problem is that `updateSumDataSet` gets called before DiscreteModel has updated all of the amplitudes, so it fails this assertion:

```js
  assert && assert( _.every( harmonicPlots, plot => plot.dataSet.length === numberOfPoints ),
    'all data sets must have the same number of points' );
```

**Comment by pixelzoom** [comment]
Hmmm... If what I described in the previous comment is the cause, then why does this fail only with the "wave packet" preset, and not the other presets?

**Comment by pixelzoom** [comment]
This is still occurring infrequently:

```
fourier-making-waves : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1609983729528/fourier-making-waves/fourier-making-waves_en.html?continuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1609983729528%22%2C%22timestamp%22%3A1609987409820%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: all data sets must have the same number of points
Error: Assertion failed: all data sets must have the same number of points
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1609983729528/assert/js/assert.js:25:13)
at createSumDataSet (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1609983729528/fourier-making-waves/js/discrete/view/HarmonicsChart.js:317:13)
at updateSumDataSet (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1609983729528/fourier-making-waves/js/discrete/view/HarmonicsChart.js:246:30)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1609983729528/fourier-making-waves/js/discrete/view/HarmonicsChart.js:110:9
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1609983729528/axon/js/TinyEmitter.js:71:18)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1609983729528/axon/js/Property.js:280:25)
at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1609983729528/axon/js/Property.js:178:14)
at NumberProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1609983729528/axon/js/Property.js:350:32)
at updateAmplitudes (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1609983729528/fourier-making-waves/js/discrete/model/DiscreteModel.js:108:69)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1609983729528/fourier-making-waves/js/discrete/model/DiscreteModel.js:116:54
id: Bayes Chrome
Snapshot from 1/6/2021, 6:42:09 PM
```

**Comment by pixelzoom** [comment]
To reproduce this Error manually (as of 1.0.0-dev.15 and b09960089e729b8244213ed62c1f528702e6e6d4):

1. Run the sim with ?ea
2. Go to Discrete screen
3. Select "Wave packet" from the Waveform combo box
4. Change number of harmonics to 10
5. Change number of harmonics to 11

**Comment by pixelzoom** [comment]
Fixed as part of https://github.com/phetsims/fourier-making-waves/commit/28aec4519d46a278e8de4fb8f9a9e39834c45479.  Closing.
