### ISSUE TITLE
CT: should have type: PhetioEngineIO in allTypes. May need grunt update?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#27]
This started occurring ~4:12 PM on 12/11/2020.  Assigning to the PhET-iO team.

```
fourier-making-waves : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607733564814/studio/?sim=fourier-making-waves&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1607733564814%22%2C%22timestamp%22%3A1607734869208%7D
Uncaught Error: should have type: PhetioEngineIO in allTypes. May need grunt update?
Error: should have type: PhetioEngineIO in allTypes. May need grunt update?
at window.assert (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607733564814/phet-io-wrappers/common/js/assert.js:32:13)
at getCreator (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607733564814/studio/js/PhetioElementView.js:821:13)
at new PhetioElementView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607733564814/studio/js/PhetioElementView.js:46:21)
at Studio.updateInstancePanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607733564814/studio/js/studio.js:192:28)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607733564814/studio/js/studio.js:82:12
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607733564814/axon/js/TinyEmitter.js:71:18)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607733564814/axon/js/Property.js:280:25)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607733564814/axon/js/Property.js:178:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607733564814/axon/js/Property.js:350:32)
at Select.selectInTreeAndRerender (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607733564814/studio/js/Select.js:130:41)
id: Bayes Chrome
Snapshot from 12/11/2020, 5:39:24 PM
```

**Comment by zepumph** [comment]
Thanks for the report. This is occurring because of work done in https://github.com/phetsims/phet-io/issues/1712 where phetioEngine is added to studio before the sim has started, and before its type (PhetioEngineIO) is given to studio, which occurs once the sim is launched. The bug itself is that studio fuzz was naive, and never starts, instead it uses its list of possible fuzzable actions as its starting logic. Formalizing its start around when the sim starts feels better to me. @samreid, please review.

**Comment by samreid** [comment]
I added a question in https://github.com/phetsims/phet-io/issues/1712, let's continue the review there.

**Comment by zepumph** [comment]
Sounds good. Over to @pixelzoom to close if fixed on CT.

**Comment by pixelzoom** [comment]
I'm not familiar with what the problem was here, so can't review anything.  But I can confirm that this is no longer occurring in CT, so closing.
