### ISSUE TITLE
CT: Cannot read property includes of undefined

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fourier-making-waves#42]
```
fourier-making-waves : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/fourier-making-waves/fourier-making-waves_en.html?continuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1611027948396%22%2C%22timestamp%22%3A1611056439321%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read property 'includes' of undefined
TypeError: Cannot read property 'includes' of undefined
at WavelengthCalipersNode.interruptDrag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/fourier-making-waves/js/discrete/view/MeasurementToolNode.js:128:37)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/fourier-making-waves/js/discrete/view/MeasurementToolNode.js:102:14
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/axon/js/TinyEmitter.js:71:18)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/axon/js/Property.js:280:25)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/axon/js/Property.js:178:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/axon/js/DerivedProperty.js:91:13)
at TinyStaticProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/axon/js/TinyEmitter.js:71:18)
at TinyStaticProperty.notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/axon/js/TinyProperty.js:145:10)
at WavelengthCalipersNode.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/scenery/js/nodes/Node.js:1238:36)
at DiscreteScreenView.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/scenery/js/nodes/Node.js:1186:29)
id: Bayes Chrome
Snapshot from 1/18/2021, 8:45:48 PM

----------------------------------

fourier-making-waves : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/fourier-making-waves/fourier-making-waves_en.html?continuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1611027948396%22%2C%22timestamp%22%3A1611029406024%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read property 'includes' of undefined
TypeError: Cannot read property 'includes' of undefined
at WavelengthCalipersNode.interruptDrag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/fourier-making-waves/js/discrete/view/MeasurementToolNode.js:128:37)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/fourier-making-waves/js/discrete/view/MeasurementToolNode.js:102:14
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/axon/js/TinyEmitter.js:71:18)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/axon/js/Property.js:280:25)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/axon/js/Property.js:178:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/axon/js/DerivedProperty.js:91:13)
at TinyStaticProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/axon/js/TinyEmitter.js:71:18)
at TinyStaticProperty.notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/axon/js/TinyProperty.js:145:10)
at WavelengthCalipersNode.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/scenery/js/nodes/Node.js:1238:36)
at DiscreteScreenView.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/scenery/js/nodes/Node.js:1186:29)
id: Bayes Chrome
Snapshot from 1/18/2021, 8:45:48 PM

----------------------------------

fourier-making-waves : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/studio/?sim=fourier-making-waves&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1611027948396%22%2C%22timestamp%22%3A1611059773778%7D
Uncaught Error: Uncaught TypeError: Cannot read property 'includes' of undefined
TypeError: Cannot read property 'includes' of undefined
at WavelengthCalipersNode.interruptDrag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/fourier-making-waves/js/discrete/view/MeasurementToolNode.js:128:37)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/fourier-making-waves/js/discrete/view/MeasurementToolNode.js:102:14
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/axon/js/TinyEmitter.js:71:18)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/axon/js/Property.js:280:25)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/axon/js/Property.js:178:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/axon/js/DerivedProperty.js:91:13)
at TinyStaticProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/axon/js/TinyEmitter.js:71:18)
at TinyStaticProperty.notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/axon/js/TinyProperty.js:145:10)
at WavelengthCalipersNode.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/scenery/js/nodes/Node.js:1238:36)
at DiscreteScreenView.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/scenery/js/nodes/Node.js:1186:29)
id: Bayes Chrome
Snapshot from 1/18/2021, 8:45:48 PM

----------------------------------

fourier-making-waves : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/fourier-making-waves/fourier-making-waves_en.html?continuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1611027948396%22%2C%22timestamp%22%3A1611030069082%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught TypeError: Cannot read property 'includes' of undefined
TypeError: Cannot read property 'includes' of undefined
at WavelengthCalipersNode.interruptDrag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/fourier-making-waves/js/discrete/view/MeasurementToolNode.js:128:37)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/fourier-making-waves/js/discrete/view/MeasurementToolNode.js:102:14
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/axon/js/TinyEmitter.js:71:18)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/axon/js/Property.js:280:25)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/axon/js/Property.js:178:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/axon/js/DerivedProperty.js:91:13)
at TinyStaticProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/axon/js/TinyEmitter.js:71:18)
at TinyStaticProperty.notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/axon/js/TinyProperty.js:145:10)
at WavelengthCalipersNode.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/scenery/js/nodes/Node.js:1238:36)
at DiscreteScreenView.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/scenery/js/nodes/Node.js:1186:29)
id: Bayes Chrome
Snapshot from 1/18/2021, 8:45:48 PM
```

**Comment by pixelzoom** [comment]
Failing at line 128 of MeasurementToolNode:

```js
  interruptDrag() {
    if ( this.dragListener.isPressed ) {
      this.interruptSubtreeInput();
      const harmonic = this.harmonicProperty.value;
128   if ( this.emphasizedHarmonics.includes( harmonic ) ) {
        this.emphasizedHarmonics.remove( harmonic );
      }
    }
  }
```

I neglected to define `this.emphasizedHarmonics` when this bit of code was moved from subclasses to base class.  Fixed in the above commit. Closing.
