### ISSUE TITLE
CT: Assertion failed: reentry detected

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#51]
```
fourier-making-waves : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/fourier-making-waves/fourier-making-waves_en.html?continuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1616082139562%22%2C%22timestamp%22%3A1616083359712%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: reentry detected, value=0,-1.5,0,-1.5,1.5,1.5,0.8373983739837381,-1.0664564096067142,1.5,-1.5,0.3712263989343523, oldValue=0,-1.5,1.008130081300814,-1.5,1.5,1.5,0.8373983739837381,-1.0664564096067142,1.5,-1.5,0.3712263989343523
Error: Assertion failed: reentry detected, value=0,-1.5,0,-1.5,1.5,1.5,0.8373983739837381,-1.0664564096067142,1.5,-1.5,0.3712263989343523, oldValue=0,-1.5,1.008130081300814,-1.5,1.5,1.5,0.8373983739837381,-1.0664564096067142,1.5,-1.5,0.3712263989343523
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/assert/js/assert.js:25:13)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/axon/js/Property.js:291:15)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/axon/js/Property.js:191:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/axon/js/DerivedProperty.js:111:13)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/axon/js/TinyEmitter.js:86:18)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/axon/js/Property.js:294:25)
at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/axon/js/Property.js:191:14)
at NumberProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/axon/js/Property.js:364:32)
at FourierSeries.setAmplitudes (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/fourier-making-waves/js/common/model/FourierSeries.js:140:51)
at guessAmplitudesListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/fourier-making-waves/js/waveGame/model/WaveGameHarmonicsChart.js:41:72)
id: Bayes Chrome
Snapshot from 3/18/2021, 9:42:19 AM
```

**Comment by pixelzoom** [comment]
This does not appear to be specific to the "pan-and-zoom-fuzz : unbuilt" test.  I also see it occurring with these tests:

fourier-making-waves : fuzz : unbuilt
fourier-making-waves : fuzz : unbuilt : assertSlow
fourier-making-waves : phet-io-fuzz : unbuilt
fourier-making-waves : phet-io-studio-fuzz : unbuilt

**Comment by pixelzoom** [comment]
Fix pushed in the above commit.  Need to listen to each harmonic's amplitude individually, instead of trying to set all amplitudes at once.   

Tested with `brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=false`

I'll leave this open to verify that CT agrees.

**Comment by pixelzoom** [comment]
CT agrees that this is fixed. Closing.
