### ISSUE TITLE
CT: value failed isValidValue

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#67]
Looks like this started around 5/24/2021 @ 5:17pm.

`?ea&brand=phet-io&phetioStandalone`

```
fourier-making-waves : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621955401129/fourier-making-waves/fourier-making-waves_en.html?continuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1621955401129%22%2C%22timestamp%22%3A1621956758231%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: value failed isValidValue: 3
Error: Assertion failed: value failed isValidValue: 3
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621955401129/assert/js/assert.js:25:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621955401129/axon/js/ValidatorDef.js:324:39)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621955401129/axon/js/validate.js:36:18)
at NumberProperty.validateNumberProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621955401129/axon/js/NumberProperty.js:105:9)
at rangePropertyObserver (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621955401129/axon/js/NumberProperty.js:122:43)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621955401129/axon/js/TinyEmitter.js:86:18)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621955401129/axon/js/Property.js:270:23)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621955401129/axon/js/Property.js:320:47
at NumberProperty.setValueAndRange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621955401129/axon/js/NumberProperty.js:219:29)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621955401129/fourier-making-waves/js/waveGame/model/WaveGameLevel.js:185:46
id: Bayes Chrome
Snapshot from 5/25/2021, 9:10:01 AM
```

**Comment by pixelzoom** [comment]
The value `3` is apparently not significant:

```
fourier-making-waves : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621967363346/fourier-making-waves/fourier-making-waves_en.html?continuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1621967363346%22%2C%22timestamp%22%3A1621968477002%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: value failed isValidValue: 5
Error: Assertion failed: value failed isValidValue: 5
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621967363346/assert/js/assert.js:25:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621967363346/axon/js/ValidatorDef.js:324:39)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621967363346/axon/js/validate.js:36:18)
at NumberProperty.validateNumberProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621967363346/axon/js/NumberProperty.js:105:9)
at rangePropertyObserver (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621967363346/axon/js/NumberProperty.js:122:43)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621967363346/axon/js/TinyEmitter.js:86:18)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621967363346/axon/js/Property.js:270:23)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621967363346/axon/js/Property.js:320:47
at NumberProperty.setValueAndRange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621967363346/axon/js/NumberProperty.js:219:29)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621967363346/fourier-making-waves/js/waveGame/model/WaveGameLevel.js:185:46
id: Bayes Chrome
Snapshot from 5/25/2021, 12:29:23 PM
```

**Comment by pixelzoom** [comment]
This is failing in WaveGameLevel.js as `amplitudesProperty` goes through intermediate states.

**Comment by pixelzoom** [comment]
Fixed in the above commit. Closing.
