### ISSUE TITLE
CT: iframe api failed

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#75]
This error occurred for 3 consecutive CT cycles on 6/8/2021, then it went away.  No idea why it might have occurred, but I'm recording it here in case it wasn't a transient problem.  I will wait to investigate.

```
fourier-making-waves : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623173371009/phet-io-wrappers/phet-io-wrappers-tests.html?sim=fourier-making-waves
11 out of 12 tests passed. 1 failed.
SimTests: fourier-making-waves: iframe api failed:
Uncaught Error: Assertion failed: getUniqueTrail found 0 matching trails for the predicate
Error: Assertion failed: getUniqueTrail found 0 matching trails for the predicate
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623173371009/assert/js/assert.js:25:13)
at WaveGameRewardNode.getUniqueTrail (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623173371009/scenery/js/nodes/Node.js:5366:17)
at WaveGameRewardNode.getScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623173371009/vegas/js/RewardNode.js:189:17)
at WaveGameRewardNode.initialize (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623173371009/vegas/js/RewardNode.js:214:30)
at RewardNode.initializer (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623173371009/vegas/js/RewardNode.js:115:35)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623173371009/axon/js/TinyEmitter.js:86:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623173371009/axon/js/Emitter.js:39:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623173371009/axon/js/Action.js:227:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623173371009/axon/js/Emitter.js:64:19)
at PhetioStateEngine.setState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1623173371009/phet-io/js/PhetioStateEngine.js:252:26)
```

**Comment by pixelzoom** [comment]
This never occurred again.  So I'm guessing that something in PhET-iO was temporarily broke, then fixed. 

Closing.
